/**
 * Dati completi di tutte le mostre di Adele Lo Feudo
 * Estratti dal frontend per il backoffice
 */

import { Exhibition } from './content-api';

export const allExhibitions: Exhibition[] = [
  {
    id: 1,
    slug: 'unisono',
    title: 'UNISONO',
    subtitle: 'Personale di Adele Lo Feudo',
    location: 'Loggia dei Lanari, Piazza Matteotti 18, Perugia',
    date: '14/03/2024 - 30/03/2024',
    description: 'Una mostra che esplora l\'unità tra l\'artista e la sua opera, dove ogni pezzo racconta una storia di armonia e connessione profonda con la materia.',
    info: 'Inaugurazione della mostra Giovedì 14 Marzo 2024, ore 18:00. Sarà presente l\'Assessore alla Cultura del Comune di Perugia, Leonardo Varasano. Orari di apertura 15:30 - 19:30. Sabato e Domenica 10:30 - 13:30 / 16:00 - 19:30',
    order_index: 1,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 2,
    slug: 'ritorno',
    title: 'RITORNO',
    subtitle: 'Personale di Adele Lo Feudo',
    location: 'Museo a Cielo Aperto di Camo (CN)',
    date: '3-24 Agosto 2025',
    description: 'Un viaggio attraverso l\'origine e il ritorno, dove l\'artista esplora le radici della propria espressione artistica in un dialogo continuo tra passato e presente.',
    info: 'Vernissage 3 agosto, ore 10:30. In esposizione fino al 24 agosto 2025',
    website: 'https://ritorno.adelelofeudo.com/',
    order_index: 2,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 3,
    slug: 'fornace-pasquinucci',
    title: 'Fornace Pasquinucci',
    subtitle: 'Mostra Personale',
    location: 'Fornace Pasquinucci, Capraia e Limite',
    date: 'Dicembre 2024',
    description: 'Una mostra che celebra la tradizione ceramica toscana attraverso opere che dialogano con lo spazio industriale della storica fornace.',
    order_index: 3,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 4,
    slug: 'amaci-giornata-contemporaneo',
    title: 'AMACI Giornata del Contemporaneo',
    subtitle: 'Ventesima Edizione',
    location: 'Italia',
    date: '12 Ottobre 2024',
    description: 'Partecipazione alla ventesima edizione della Giornata del Contemporaneo, evento nazionale dedicato all\'arte contemporanea italiana.',
    order_index: 4,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 5,
    slug: 'amor',
    title: 'Amor',
    subtitle: 'Basilica di San Domenico',
    location: 'Basilica di San Domenico, Perugia',
    date: 'Maggio 2024',
    description: 'Una riflessione sull\'amore nelle sue molteplici forme, presentata nello spazio sacro della Basilica di San Domenico.',
    order_index: 5,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 6,
    slug: 'negli-occhi-delle-donne',
    title: 'Negli occhi delle donne',
    subtitle: 'Casa Museo Antonio Ligabue',
    location: 'Casa Museo Antonio Ligabue, Gualtieri',
    date: '5-27 Agosto 2023',
    description: 'Un omaggio alla figura femminile, esposto nella casa dove il grande maestro Ligabue trovava rifugio. Uno sguardo intimo sull\'universo femminile attraverso ritratti intensi e materici.',
    order_index: 6,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 7,
    slug: 'fragile-forte',
    title: 'FragileForte',
    subtitle: 'Ex Chiesa della Misericordia',
    location: 'Ex Chiesa della Misericordia, Perugia',
    date: '4-15 Marzo 2023',
    description: 'Un\'esplorazione della dualità umana tra fragilità e forza, dove ogni opera rappresenta la tensione tra vulnerabilità e resilienza.',
    order_index: 7,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 8,
    slug: 'mostra-personale-bergamo',
    title: 'Mostra Personale',
    subtitle: 'Ex Ateneo',
    location: 'Ex Ateneo, Bergamo',
    date: '25 Nov - 11 Dic 2022',
    description: 'Una retrospettiva delle opere più significative dell\'artista, presentata nello storico spazio dell\'Ex Ateneo di Bergamo.',
    order_index: 8,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 9,
    slug: 'amore-e-vita',
    title: 'Amore e Vita',
    subtitle: 'Casa Museo Antonio Ligabue',
    location: 'Casa Museo Antonio Ligabue, Gualtieri',
    date: '6 Ago - 4 Set 2022',
    description: 'Una celebrazione della vita e dell\'amore attraverso opere che esplorano i temi universali dell\'esistenza umana.',
    order_index: 9,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 10,
    slug: 'un-cuore-solo',
    title: 'Un cuore solo',
    subtitle: 'Sala Cannoniera - Rocca Paolina',
    location: 'Sala Cannoniera - Rocca Paolina, Perugia',
    date: '31 Ott - 14 Nov 2020',
    description: 'Una mostra che parla di unità e connessione, presentata durante il periodo pandemico come messaggio di speranza e solidarietà.',
    order_index: 10,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 11,
    slug: 'varese-1902-storie-donne',
    title: 'Varese 1902 - Storie di donne',
    subtitle: 'Battistero di Velate',
    location: 'Battistero di Velate, Varese',
    date: '23 Nov - 8 Dic 2019',
    description: 'Storie di donne del passato rivivono attraverso l\'arte, in un dialogo tra memoria storica e contemporaneità.',
    order_index: 11,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 12,
    slug: 'al-di-sopra-degli-stagni',
    title: 'Al di sopra degli stagni',
    subtitle: 'Archivio di Stato',
    location: 'Archivio di Stato, Pesaro',
    date: '14 Ott - 3 Nov 2018',
    description: 'Un\'esplorazione poetica della natura e della sua relazione con l\'anima umana.',
    order_index: 12,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 13,
    slug: 'columbus-day-gala',
    title: 'Columbus Day Gala',
    subtitle: 'Manhattan Midtown Hilton',
    location: 'Manhattan Midtown Hilton, New York',
    date: '7 Ottobre 2017',
    description: 'Partecipazione al prestigioso Columbus Day Gala a New York, portando l\'arte italiana nel cuore di Manhattan.',
    order_index: 13,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 14,
    slug: 'per-giungere-fino-a-te',
    title: 'Per giungere fino a te',
    subtitle: 'Ex Chiesa della Misericordia',
    location: 'Ex Chiesa della Misericordia, Perugia',
    date: '23 Set - 4 Ott 2017',
    description: 'Un viaggio artistico verso l\'altro, un percorso di ricerca e incontro attraverso la materia pittorica.',
    order_index: 14,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 15,
    slug: 'i-maccaturi',
    title: 'I Maccaturi',
    subtitle: 'Museo Civico',
    location: 'Museo Civico, Altomonte',
    date: '15 Ott - 30 Nov 2016',
    description: 'Una mostra dedicata alle tradizioni e alla cultura calabrese, riscoperte attraverso uno sguardo contemporaneo.',
    order_index: 15,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 16,
    slug: 'presenze-assenze-io-sono',
    title: 'Presenze / Assenze Io Sono!',
    subtitle: 'Museo a Cielo Aperto',
    location: 'Museo a Cielo Aperto, Camo',
    date: '26 Giu - 26 Lug 2016',
    description: 'Un\'indagine sulla presenza e l\'assenza, sull\'essere e il non essere, attraverso installazioni e opere pittoriche.',
    order_index: 16,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 17,
    slug: 'human-rights',
    title: 'Human Rights?',
    subtitle: 'Fondazione Opera Campana dei Caduti',
    location: 'Fondazione Opera Campana dei Caduti, Rovereto',
    date: 'Mag - Set 2016',
    description: 'Una riflessione sui diritti umani attraverso l\'arte, in uno dei luoghi simbolo della memoria italiana.',
    order_index: 17,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 18,
    slug: 'arte-confronto-laguna',
    title: 'Arte a confronto in laguna',
    subtitle: 'JW Marriott Venice Resort',
    location: 'JW Marriott Venice Resort, Venezia',
    date: '2 Apr - 2 Mag 2016',
    description: 'Un dialogo artistico nella suggestiva cornice veneziana, dove l\'arte contemporanea incontra la tradizione.',
    order_index: 18,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 19,
    slug: 'messi-a-nudo',
    title: 'Messi a Nudo',
    subtitle: 'Galleria Spazio Monticini',
    location: 'Galleria Spazio Monticini, Montevarchi',
    date: 'Dicembre 2015',
    description: 'Un\'esposizione che svela l\'essenza umana, togliendo i veli e le maschere sociali.',
    order_index: 19,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 20,
    slug: 'forma-et-imago',
    title: 'Forma et Imago',
    subtitle: 'Palazzo Ducale',
    location: 'Palazzo Ducale, Revere',
    date: 'Giugno 2015',
    description: 'Un\'esplorazione del rapporto tra forma e immagine, tra materia e rappresentazione.',
    order_index: 20,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 21,
    slug: 'motus-terrae',
    title: 'Motus Terrae',
    subtitle: 'Museo Parco Archeologico Compsa',
    location: 'Museo Parco Archeologico Compsa, Conza della Campania',
    date: 'Dicembre 2014',
    description: 'Un omaggio alla terra e alle sue forze primordiali, in dialogo con il patrimonio archeologico.',
    order_index: 21,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 22,
    slug: 'qui-non-si-muore',
    title: 'Qui non si muore!',
    subtitle: 'Galleria Via Cavour 85',
    location: 'Galleria Via Cavour 85, Arezzo',
    date: 'Novembre 2014',
    description: 'Un messaggio di vita e speranza attraverso l\'arte, un inno alla resilienza dell\'anima umana.',
    order_index: 22,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 23,
    slug: 'un-petalo-rosa',
    title: 'Un petalo rosa',
    subtitle: 'La Casa di Roberta',
    location: 'Perugia e Cosenza',
    date: 'Ott 2013 Perugia / Nov-Dic 2013 Cosenza',
    description: 'Una mostra itinerante dedicata alla sensibilizzazione contro la violenza sulle donne.',
    order_index: 23,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 24,
    slug: 'riflessioni',
    title: 'Riflessioni',
    subtitle: 'Archidoro Luoghi d\'Arte',
    location: 'Archidoro Luoghi d\'Arte, Cetona',
    date: 'Settembre 2013',
    description: 'Un momento di riflessione attraverso l\'arte, dove ogni opera diventa specchio dell\'anima.',
    order_index: 24,
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];